#!/usr/bin/env bash
set -euo pipefail

# constructs a PEP 440 version string from a Git repository, following the spirit of Go module
# pseudo-versions (https://golang.org/ref/mod#pseudo-versions): a v* tag on HEAD yields that exact
# release; otherwise a PEP 440 .dev pseudo-version is derived from the nearest ancestor tag.

shopt -s extglob

version="$(git tag --sort=-v:refname --points-at HEAD -l 'v*')" || exit 1
IFS=$'\n' read -r version <<< "$version"

case "$version" in
'');;
v+([0-9]).+([0-9]).+([0-9])?(-pre)?([+]*)) echo "${version:1}" && exit 0;;
*) exit 1;;
esac

version="$(git tag --sort=-v:refname --merged HEAD -l 'v*')" || exit 1
IFS=$'\n' read -r version <<< "$version"

case "$version" in
'')
    base="0.0.0"
    ;;
v+([0-9]).+([0-9]).+([0-9])-pre?([+]*))
    base="${version#v}"
    base="${base%[+]*}"
    ;;
v+([0-9]).+([0-9]).+([0-9])?([+]*))
    base="${version#v}"
    base="${base%[+]*}"
    base="${base%.*}.$((${base##*.} + 1))"
    ;;
*)
    exit 1
    ;;
esac

timestamp="$(git show -s --date=format:"%Y%m%d%H%M%S" --format=%cd HEAD)"
echo "${base}.dev${timestamp}+$(git rev-parse --short=12 HEAD)"
